config/routes.rb
Rails.application.routes.draw do

  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  get 'my_friends', to: "spree_users#my_friends"
  resources :spree_users, only: [:show]
  resources :users, only: [:show]
  resources :friendships
  get 'search_friends', to: "spree_users#search"
  post 'add_friend', to: "users#add_friend"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/added_item.rb
class AddedItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
  belongs_to :user

  has_many :user_items
  has_many :users, :through => :user_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user, :class_name => 'Spree::User', optional: true
  belongs_to :friend, :class_name => 'Spree::User'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_members
  has_many :users, :through => :group_members
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :added_items
  has_many :orders, :through => :added_items
end

app/models/order_member.rb
class OrderMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
end

app/models/spree/order_decorator.rb
module Spree::OrderDecorator
  Spree::Order.class_eval do
    has_many :order_members
    has_many :users, :through => :order_members

    has_many :added_items
    has_many :items, :through => :added_items
  end
end

app/models/spree/user_decorator.rb
module Spree::UserDecorator
  Spree::User.class_eval do
    has_many :friendships
    has_many :friends, through: :friendships

    has_many :group_members
    has_many :groups, :through => :group_members

    has_many :order_members
    has_many :spree_orders, :through => :order_members

    has_many :user_items
    has_many :added_items, :through => :user_items

    belongs_to :referred_by, optional: true, :class_name => "Spree::User", :foreign_key => "referred_by_user_id"
    has_many :referrals, :class_name => "Spree::User", :foreign_key => "referred_by_user_id"

    validates :referred_by_user_id, presence: true, allow_nil: true

    def self.search(param)
      param.to_s.strip!
      param.to_s.downcase!
      to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
      return nil unless to_send_back
      to_send_back
    end

    def self.first_name_matches(param)
      matches('first_name', param)
    end

    def self.last_name_matches(param)
      matches('last_name', param)
    end

    def self.email_matches(param)
      matches('email', param)
    end

    def self.matches(field_name, param)
      Spree::User.where("#{field_name} like?", "%#{param}%")
    end

    def except_current_user(users)
      users.reject{|user| user.id == self.id}
    end

    def not_friends_with?(friend_id)
      friendships.where(friend_id: friend_id).count < 1
    end

  end
end

app/models/spree_order.rb
class SpreeOrder < ActiveRecord::Base
  has_many :order_members
  has_many :users, :through => :order_members

  has_many :added_items
  has_many :items, :through => :added_items
end

app/models/user_item.rb
class UserItem < ActiveRecord::Base
  belongs_to :added_item
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Spree::AuthenticationHelpers
end

app/controllers/spree/users_controller_decorator.rb
module Spree::UsersControllerDecorator
  Spree::Admin::UsersController.class_eval do
    def my_friends
      @friendships = current_spree_user.friends
    end

    def search
      @users = User.search(params[:search_param])

      if params[:search_param].blank?
        flash.now[:danger] = "You have entered an empty string"
      else
        @users = User.search(params[:search_param])
        @users = current_user.except_current_user(@users)
        flash.now[:danger] = "No users to math this search criteria" if @users.blank?
      end

      respond_to do |format|
        format.js { render partial: 'friends/result' }
      end
    end

    def add_friend
      @friend = User.find(params[:friend])
      current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      flash[:success] = "Friend was successfully added"
    else
      flash[:danger] = "Something went wrong with friend request"
    end
    redirect_to my_friends_path
    end

    def show
      @user = User.find(params[:id])
    end
  end
end

app/controllers/spree_users_controller.rb
class SpreeUsersController < ApplicationController
  def my_friends
    @friendships = current_spree_user.friends
  end

  def search
    @spree_users = SpreeUser.search(params[:search_param])
    render json: @spree_users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spree/base_helper_decorator.rb
module Spree::BaseHelperDecorator
  def logo(image_path = Spree::Config[:logo], img_options: {})
    link_to image_tag(image_path, img_options), spree.root_path
  end

  def nav_tree(root_taxon, current_taxon, max_level = 1)
    return '' if max_level < 1 || root_taxon.children.empty?
    content_tag :ul, class: 'dropdown-menu' do
      taxons = root_taxon.children.map do |taxon|
        css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'active' : nil
        content_tag :li, class: css_class do
         link_to(taxon.name, seo_url(taxon)) +
           taxons_tree(taxon, current_taxon, max_level - 1)
        end
      end
      safe_join(taxons, "\n")
    end
  end
end

app/views/friends/_lookup.html.erb
<h3> Search for friends </h3>
<div id="friend-lookup">
  <%= form_tag search_friends_path, remote: true, method: :get, id: "friend-lookup-form" do %>
  <div class= "form-group row no-padding text-center col-md-12">
      <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter name or email", autofocus: true, class: "form-control search-box input-lg" %>
  </div>
    <div class="col-md-12">
      <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
        <i class="fa fa-search"></i> Search
      <% end %>
    </div>
</div>
<% end %>

<div id="results">
  <%= render 'friends/result' %>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<% if @users %>
  <% if @users.size > 0 %>
    <div id="friend-lookup-results" class= "well results-block col-md-10">
      <table class= "search-results-table col-md-12">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><strong>Name: </strong> <%= user.full_name %></td
              <td><strong>Email: </strong> <%= user.email %></td>
              <td><strong>Profile: </strong> <%= link_to "View Profile", "#", class: "btn btn-xs btn-success"%>
                <% if current_user.not_friends_with?(user.id) %>
                  <%= link_to "Add as my Friend", add_friend_path(user: current_user, friend: user),
                                               class: "btn btn-xs btn-success", method: :post %>
                <% else %>
                  <span class="label label-primary">
                    You are already friends
                  </span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

app/views/spree/checkout/registration.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @user } %>
<div class='panel panel-default'
  <div class='panel-heading'>
    <%= I18n.t('spree.registration') %>
  </div>
  <div class='panel-body'>
    <div id="registration" class='row' data-hook>
      <div id="account" class="col-md-6">
        <div class='col-md-8 col-md-offset-2'>
          <%= render partial: 'spree/user_sessions/login' %>
        </div>
      </div>
      <% if Spree::Config[:allow_guest_checkout] %>
        <div id="guest_checkout" data-hook class="col-md-6">
          <div class='col-md-8 col-md-offset-2'>
            <div class='alert alert-info'>
              <%= I18n.t('spree.guest_user_account') %>
            </div>
            <% if flash[:registration_error] %>
              <div class='flash error'><%= flash[:registration_error] %></div>
            <% end %>
            <%= form_for @order, url: update_checkout_registration_path, method: :put, html: { id: 'checkout_form_registration' } do |f| %>
              <div class='form-group'>
                <%= f.label :email, I18n.t('spree.email') %>
                <%= f.email_field :email, class: 'title form-control' %>
              </div>
              <div class='actions'>
                <%= f.submit I18n.t('spree.continue'), class: 'btn btn-primary btn-block' %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/home/index.html.erb
<div data-hook="homepage_products">
  <% cache(cache_key_for_products) do %>
    <%= render :partial => 'spree/shared/products', :locals => {:products => @products} %>
  <% end %>
</div>

app/views/spree/layouts/spree_application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->
  <head data-hook="inside_head">
    <%= render partial: 'spree/shared/head' %>
  </head>
  <body class="<%= body_class %> hello there" id="<%= @body_id || 'default' %>" data-hook="body">

    <%= render partial: 'spree/shared/header' unless devise_controller?%>

  <div class="container">

      <div id="wrapper" class="row" data-hook>

        <%= taxon_breadcrumbs(@taxon) %>

        <%= render partial: 'spree/shared/sidebar' if content_for? :sidebar %>

        <div id="content" class="columns <%= !content_for?(:sidebar) ? "sixteen" : "twelve omega" %>" data-hook>
          <%= flash_messages %>
          <%= yield %>
        </div>

        <%= yield :templates %>

      </div>

      <%= render partial: 'spree/shared/footer' %>

    </div>

  </body>
</html>

app/views/spree/orders/_form.html.erb
<% order = order_form.object %>
<%= render 'spree/shared/error_messages', target: order %>
<table id="cart-detail" class='table' data-hook>
  <thead>
    <tr data-hook="cart_items_headers">
      <th class="cart-item-description-header" colspan="2"><%= t('spree.item') %></th>
      <th class="cart-item-price-header"><%= t('spree.price') %></th>
      <th class="cart-item-quantity-header"><%= t('spree.qty') %></th>
      <th class="cart-item-total-header"><%= t('spree.total') %></th>
      <th class="cart-item-delete-header"></th>
    </tr>
  </thead>
  <tbody id="line_items" data-hook>
    <%= render partial: 'spree/orders/line_item', collection: order.line_items, locals: { order_form: order_form } %>
  </tbody>
  <% if order.adjustments.nonzero.exists? || order.line_item_adjustments.nonzero.exists? || order.shipment_adjustments.nonzero.exists? || order.shipments.any? %>
    <tr class="cart-subtotal">
      <td colspan="4" align='right'><h5><%= t('spree.cart_subtotal', count: order.line_items.sum(:quantity)) %></h5></td>
      <td colspan><h5><%= order.display_item_total %></h5></td>
      <td></td>
    </tr>
    <%= render "spree/orders/adjustments" %>
  <% end %>
  <tr class="cart-total">
    <td colspan="4" align='right'><h5><%= t('spree.total') %></h5></td>
    <td colspan><h5><%= order.display_total %></h5></td>
    <td></td>
  </tr>
</table>

app/views/spree/orders/_line_item.html.erb
<% variant = line_item.variant -%>
<%= order_form.fields_for :line_items, line_item do |item_form| -%>
  <tr class="<%= cycle('', 'alt') %> line-item">
    <td class="cart-item-image" data-hook="cart_item_image">
      <%= link_to(render('spree/shared/image',
                         image: (variant.gallery.images.first || variant.product.gallery.images.first),
                         size: :small), variant.product) %>
    </td>
    <td class="cart-item-description" data-hook="cart_item_description">
      <h4><%= link_to line_item.name, product_path(variant.product) %></h4>
      <%= variant.options_text %>
      <% if line_item.insufficient_stock? %>
        <span class="out-of-stock">
          <%= t('spree.out_of_stock') %>&nbsp;&nbsp;<br />
        </span>
      <% end %>
      <span class="line-item-description" data-hook="line_item_description">
        <%= line_item_description_text(line_item.description) %>
      </span>
    </td>
    <td class="cart-item-price" data-hook="cart_item_price">
      <%= line_item.single_money.to_html %>
    </td>
    <td class="cart-item-quantity" data-hook="cart_item_quantity">
      <%= item_form.number_field :quantity, min: 0, class: "line_item_quantity form-control", size: 5 %>
    </td>
    <td class="cart-item-total" data-hook="cart_item_total">
      <%= line_item.display_amount.to_html unless line_item.quantity.nil? %>
    </td>
    <td class="cart-item-delete" data-hook="cart_item_delete">
      <%= link_to image_tag('icons/delete.png'), '#', class: 'delete', id: "delete_#{dom_id(line_item)}" %>
    </td>
  </tr>
<% end -%>

app/views/spree/orders/edit.html.erb
<% @body_id = 'cart' %>
<div data-hook="cart_container">
  <h1><%= t('spree.shopping_cart') %></h1>

  <% if @order.line_items.empty? %>

    <div data-hook="empty_cart">
      <p><%= t('spree.your_cart_is_empty') %></p>
      <p><%= link_to t('spree.continue_shopping'), products_path, class: 'button continue' %></p>
    </div>

  <% else %>

    <div data-hook="outside_cart_form">
      <%= form_for @order, url: update_cart_path, html: {id: 'update-cart', class: 'form-inline'} do |order_form| %>
        <div data-hook="inside_cart_form">

          <div data-hook="cart_items">
            <%= render 'spree/orders/form', order_form: order_form %>
          </div>
          <hr>
          <div class="links columns sixteen alpha omega form-group" data-hook="cart_buttons">
            <%= order_form.text_field :coupon_code, :size => 10, :placeholder => Spree.t(:coupon_code), class: 'form-control' %>
            <%= button_tag t("spree.update"), class: "primary btn btn-success", id: "update-button" %>
            <%= button_tag class: 'button checkout primary btn btn-primary', id: 'checkout-link', name: 'checkout' do %>
              <%= t('spree.checkout') %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <hr>
    <div id="empty-cart" data-hook>
      <%= form_tag empty_cart_path, method: :put do %>
        <p id="clear_cart_link" data-hook>
        <%= submit_tag t('spree.empty_cart'), class: 'button gray btn btn-default' %>
        <%= t('spree.or') %>
        <%= link_to t('spree.continue_shopping'), products_path, class: 'continue button gray btn btn-default' %>
        </p>
      <% end %>


    </div>

  <% end %>
</div>

app/views/spree/products/_cart_form.html.erb
<%= form_for :order, url: populate_orders_path, html: {class: 'form-inline' } do |f| %>
  <div id="inside-product-cart-form" data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="http://schema.org/Offer">

    <% if @product.variants_and_option_values_for(current_pricing_options).any? %>
      <div id="product-variants" class="columns five alpha">
        <h6 class="product-section-title"><%= t('spree.variants') %></h6>
        <ul>
          <% @product.variants_and_option_values_for(current_pricing_options).each_with_index do |variant, index| %>
            <li>
              <%= radio_button_tag "variant_id", variant.id, index == 0, 'data-price' => variant.price_for(current_pricing_options)  %>
              <%= label_tag "variant_id_#{ variant.id }" do %>
                <span class="variant-description">
                  <%= variant_options variant %>
                </span>
                <% if variant_price variant %>
                  <span class="price diff"><%= variant_price variant %></span>
                <% end %>

                <% unless variant.can_supply? %>
                  <span class="out-of-stock"><%= t('spree.out_of_stock') %></span>
                <% end %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <%= hidden_field_tag "variant_id", @product.master.id %>
    <% end %>

    <% if @product.price_for(current_pricing_options) and !@product.price.nil? %>
      <div data-hook="product_price" class="columns five <%= !@product.has_variants? ? 'alpha' : 'omega' %>">

        <div id="product-price">
          <h6 class="product-section-title"><%= t('spree.price') %></h6>
          <div>
            <p class="price selling lead" itemprop="price" content="<%= @product.price_for(current_pricing_options).to_d %>">
              <%= display_price(@product) %>
            </p>
            <span itemprop="priceCurrency" content="<%= current_pricing_options.currency %>"></span>
          </div>

          <% if @product.master.can_supply? %>
            <link itemprop="availability" href="http://schema.org/InStock" />
          <% elsif @product.variants.empty? %>
            <br />
            <span class="out-of-stock"><%= t('spree.out_of_stock') %></span>
          <% end %>
        </div>

        <div class="add-to-cart form-group">
          <%= number_field_tag :quantity, 1, class: 'title form-control', min: 1 %>
          <%= button_tag class: 'large primary', id: 'add-to-cart-button', class: 'btn btn-success', type: :submit do %>
            <%= t('spree.add_to_cart') %>
          <% end %>
        </div>
      </div>
    <% else %>
        <div id="product-price">
          <br>
          <div><span class="price selling" itemprop="price"><%= t('spree.product_not_available_in_this_currency') %></span></div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/spree/products/_properties.html.erb
<% unless @product_properties.empty? %>
  <h6 class="product-section-title"><%= t('spree.properties')%></h6>
  <ul id="product-properties" class="list-group" data-hook>
    <% @product_properties.each do |product_property| %>
      <% css_class = cycle('even', 'odd', name: "properties") %>
      <li class="<%= css_class %> list-group-item">
        <span class='badge'><%= product_property.value %></span>
        <%= product_property.property.presentation %>
      </li>
    <% end %>
    <% reset_cycle('properties') %>
<% end %>

app/views/spree/products/show.html.erb
<% cache [I18n.locale, current_pricing_options, @product] do %>
  <div data-hook="product_show" itemscope itemtype="http://schema.org/Product">
    <% @body_id = 'product-details' %>
    <div class='row'>
      <div class="col-md-12">
        <h1 class="product-title" itemprop="name"><%= @product.name %></h1>
      </div>
    </div>
    <div class= 'row'>
      <div class="col-md-3" data-hook="product_left_part">
        <div data-hook="product_left_part_wrap">

          <div id="product-images" data-hook="product_images">
            <div id="main-image" data-hook>
              <%= render partial: 'image' %>
            </div>
            <div id="thumbnails" data-hook>
              <%= render partial: 'thumbnails' %>
            </div>
          </div>

          <div data-hook="promotions">
            <%= render partial: 'promotions' %>
          </div>

        </div>
      </div>
      <div class="col-md-3" data-hook='product_center_part'>
        <div data-hook='product_center_part_wrap'>
          <div data-hook="product_properties">
            <%= render partial: 'properties' %>
          </div>
        </div>
      </div>
      <div class="col-md-6" data-hook="product_right_part">
        <h6 class="product-section-title"><%= Spree.t('detail')%></h6>
        <div data-hook="product_right_part_wrap" class='panel panel-default'>

          <div id="product-description" data-hook="product_description" class='panel-body'>


            <div itemprop="description" data-hook="description">
              <%= product_description(@product) rescue t('spree.product_has_no_description') %>
            </div>

            <div id="cart-form" data-hook="cart_form">
              <%= render partial: 'cart_form' %>
            </div>
          </div>
            <%= render partial: 'taxons' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/spree/shared/_header.html.erb
<nav class= "navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand amd toggle get grouped for better modile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-
target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigtion</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling-->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-
haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another Action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="seperator" class="divider"></li>
            <li><a href="#">Seperated link</a></li>
            <li role="seperator" class="divider"></li>
            <li><a href="#">One more seperated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <li id="link-to-cart" data-hook>
            <noscript>
              <%= link_to t('spree.cart'), spree.cart_path %>
            </noscript>
            &nbsp;
          </li>
          <script>Spree.fetch_cart('<%= j spree.cart_link_path %>')</script>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-
haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another Action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="seperator" class="divider"></li>
            <li><a href="#">Seperated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/spree/shared/_login.html.erb
<%= form_for Spree::User.new, as: :spree_user, url: spree.create_new_session_path do |f| %>
  <div id="password-credentials">
    <div class='form-group'>
      <%= f.label :email, I18n.t('spree.email') %>
      <%= f.email_field :email, class: 'title form-control', tabindex: 1, autofocus: true %>
    </div>
    <div class='form-group'>
      <%= f.label :password, I18n.t('spree.password') %>
      <%= f.password_field :password, class: 'title form-control', tabindex: 2 %>
    </div>
  </div>
  <div class='form-group'>
    <%= f.check_box :remember_me, tabindex: 3 %>
    <%= f.label :remember_me, I18n.t('spree.remember_me') %>
  </div>

  <div class='actions'>
    <%= f.submit I18n.t('spree.login'), class: 'btn btn-success btn-block', tabindex: 4 %>
  </div>
<% end %>

app/views/spree/shared/_products.html.erb
<%
  paginated_products = @searcher.retrieve_products if params.key?(:keywords)
  paginated_products ||= products
%>

<% content_for :head do %>
  <% if paginated_products.respond_to?(:total_pages) %>
    <%= rel_next_prev_link_tags paginated_products %>
  <% end %>
<% end %>

<div data-hook="products_search_results_heading">
  <% if products.empty? %>
    <div data-hook="products_search_results_heading_no_results_found">
      <%= t('spree.no_products_found') %>
    </div>
  <% elsif params.key?(:keywords) %>
    <div data-hook="products_search_results_heading_results_found">
      <h6 class="search-results-title"><%= t('spree.search_results', keywords: h(params[:keywords])) %></h6>
    </div>
  <% end %>
</div>

<% if products.any? %>
  <div id="products" class="inline product-listing row" data-hook>
    <% products.each do |product| %>
      <div class='col-sm-6 col-md-4'>
      <% url = spree.product_path(product, taxon_id: @taxon.try(:id)) %>
        <div id="product_<%= product.id %>" class="thumbnail <%= cycle("alpha", "secondary", "", "omega secondary", name: "classes") %>" data-hook="products_list_item" itemscope itemtype="http://schema.org/Product">
          <% cache(@taxon.present? ? [I18n.locale, current_pricing_options, @taxon, product] : [I18n.locale, current_pricing_options, product]) do %>
            <div class="product-image">
              <%= link_to(render('spree/shared/image', image: product.gallery.images.first, size: :small, itemprop: "image"), url, itemprop: 'url') %>
            </div>
            <div class='caption'>
              <h3>
                <%= link_to truncate(product.name, length: 50), url, class: 'info', itemprop: "name", title: product.name %>
              </h3>
              <p>
                <%= link_to url, class: 'btn btn-primary' do %>
                 <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                    <% if price = product.price_for(current_pricing_options) %>
                      <span class="price selling" itemprop="price" content="<%= price.to_d %>">
                        <%= price.to_html %>
                      </span>
                    <% end %>
                    <span itemprop="priceCurrency" content="<%= current_pricing_options.currency %>"></span>
                 </span>
               <% end %>
            </p>
          </div>
          <% end %>
      </div>
    </div>
    <% end %>
    <% reset_cycle("classes") %>
  </div>
<% end %>

<% if paginated_products.respond_to?(:total_pages) %>
  <%= paginate paginated_products %>
<% end %>

app/views/spree/shared/_taxonomies.html.erb
<% max_level = Spree::Config[:max_level_in_taxons_menu] || 1 %>
<nav id="taxonomies" class="sidebar-item" data-hook>
  <% @taxonomies.each do |taxonomy| %>
    <% cache [I18n.locale, taxonomy, @taxon, max_level] do %>
      <h6 class='taxonomy-root'><%= t('spree.shop_by_taxonomy', taxonomy: taxonomy.name) %></h6>
      <%= taxons_tree(taxonomy.root, @taxon, max_level) %>
    <% end %>
  <% end %>
</nav>

app/views/spree_users/my_friends.html.erb
<h1> My Friends </h1>

<%= render 'friends/lookup' %>
<% if @friendships.size > 0 %>
   <table class="table table-stripe"”>
     <thead>
          <tr>
             <th colspan= "3" class = "page-header"
             <hr>
                  <h3>My friends</h3>
             </th>
          </tr>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Actions</th>
         </tr>
      </thead>
      <tbody>
        <% @friendships.each do |friend| %>
        <tr>
          <td><%= friend.email %></td>
          <td>
            <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-s" %>
            <%= link_to 'Remove Friend', friendship_path(friend),
              :method => :delete,
              :data => { :confirm => "Are you sure?" },
              :class => "btn btn-sx btn-danger"%>
          </td>
        </tr>
	       <% end %>
      </tbody>
  </table>
<%else%>
	<div class= "row col-lg012">
    <p class="lead">You dont have any friends.</p>
	</div>
<% end %>